#!/usr/bin/env bash
#Toolchain wrapper for PVMK
#Bryan E. Topp <betopp@betopp.com> 2023
source $(dirname $0)/pvmk-vars
exec -a "$0" ${SYSROOT}/bin/$(uname -o)/$(uname -m)/pvmk-gcc -B${SYSROOT}/bin/$(uname -o)/$(uname -m)/ -B${SYSROOT}/bin/$(uname -o)/$(uname -m)/gcc/armv5te-pvmk-eabi/15.1.0 --picolibc-prefix=${SYSROOT} --specs=${SYSROOT}/armv5te-pvmk-eabi/lib/pvmk.specs "$@"
