#!/usr/bin/env bash
#Toolchain wrapper for PVMK
#Bryan E. Topp <betopp@betopp.com> 2023
source $(dirname $0)/pvmk-vars
${SYSROOT}/bin/pvmk-gcc --picolibc-prefix=${SYSROOT} --specs=${SYSROOT}/armv5te-pvmk-eabi/lib/pvmk.specs $@
