#!/usr/bin/env bash
#Toolchain wrapper for PVMK
#Bryan E. Topp <betopp@betopp.com> 2023
source $(dirname $0)/pvmk-vars
arm-none-eabi-gcc --specs=${SYSROOT}/picolibc/arm-none-eabi/lib/picolibc.specs -fno-short-enums -fsigned-char $@
